# Generated by Django 4.1.5 on 2023-01-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books_alter_shops_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.TextField(verbose_name='Название книги')),
                ('author', models.CharField(max_length=60, verbose_name='Автор книги')),
                ('client', models.CharField(max_length=60, verbose_name='ФИО покупателя')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон покупателя')),
                ('shopname', models.CharField(max_length=50, verbose_name='Название магазина')),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Каталог товаров'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Список магазинов'},
        ),
    ]
