# Generated by Django 4.1.5 on 2023-01-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orders_alter_books_options_alter_shops_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Журнал заказов'},
        ),
    ]
