# Generated by Django 4.1.5 on 2023-01-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='phone',
            field=models.CharField(default='88005553535', max_length=11, verbose_name='Название'),
        ),
    ]
