# Generated by Django 4.1.5 on 2023-01-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shops_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.CharField(default='345', max_length=10, verbose_name='Номер  заказа'),
        ),
    ]
